apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-nodeport
  labels:
    app: node-web-app-nodeport
spec:
  selector:
    matchLabels:
      app: node-web-app-nodeport
  replicas: 1
  template:
    metadata:
      labels:
        app: node-web-app-nodeport
    spec:
      containers:
        - name: node-web-app-nodeport
          image: wkd3475/node-web-app
          ports:
          - containerPort: 3000
          resources:
            limits:
              memory: "300Mi"
              cpu: "300m"
            requests:
              memory: "300Mi"
              cpu: "300m"
              # nodeSelector:
              #      workertype: worker
