apiVersion: v1
kind: Service
metadata:
  name: node-web-app-nodeport
spec:
  selector:
    app: node-web-app-nodeport
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: NodePort
